# Generated by Django 3.1.7 on 2022-01-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='name',
            new_name='company',
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
